### ISSUE TITLE
Number custom inserting thousands separators

### ISSUE THREAD

**Issue by Shirobachi** [mabeyj/trilium-collection-views#23]
Hey, 

I would like suggest add in attribute custom inserting thousands separators. So, for example, you could use it as a phone number via changing separator to `-`

**Comment by mabeyj** [comment]
I think this would be best accomplished using custom expressions (#22) when that is implemented since you would have full control over formatting values.

For phone numbers in particular, there is already an issue because there are multiple ways phone numbers can be formatted. For me locally, a common format would be `xxx-xxx-xxxx`. If I entered a phone number into an attribute as `1234567890`, then standard number formatting would yield `1,234,567,890`, and changing the separator would yield `1-234-567-890` instead of `123-456-7890`.

**Comment by Shirobachi** [comment]
Actually, when you pointed this out, I fully agree! BTW. May I ask for your e-mail address?
